-- AlterTable
ALTER TABLE "Article" ADD COLUMN "heroAlt" TEXT,
ADD COLUMN "heroCaption" TEXT,
ADD COLUMN "heroCredit" TEXT,
ADD COLUMN "heroFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "heroFocalY" DOUBLE PRECISION NOT NULL DEFAULT 50;
